require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - aws-ssm-env.gemspec

Naming/FileName:
  Exclude:
    - '**/aws-ssm-env*.rb'

Style/SingleLineMethods:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/Semicolon:
  Exclude:
    - 'spec/**/*.rb'

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/GuardClause:
  MinBodyLength: 4

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/FilePath:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 4

# don't use closable resource
RSpec/BeforeAfterAll:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MinMaxComparison:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false
