# refs: https://ybiquitous.me/blog/2022/release-gem-using-github-actions
name: Publish

on:
  workflow_dispatch:
    inputs:
      otp:
        description: "One-time password for RubyGems.org"
        required: true

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby#publishing-gems
      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --otp "${GEM_HOST_OTP_CODE}" *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.GEM_HOST_API_KEY}}"
          GEM_HOST_OTP_CODE: "${{ inputs.otp }}"
