name: Ruby Lint

on:
  push:
    branches: [master]
    paths:
      - 'ruby/**'
      - '.github/workflows/ruby-lint.yml'
  pull_request:
    paths:
      - 'ruby/**'
      - '.github/workflows/ruby-lint.yml'

defaults:
  run:
    working-directory: ruby

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          working-directory: ruby
      - name: Run rubocop
        run: bundle exec rubocop
