name: Test

on:
  push:
    branches: [master]
  pull_request:
    paths:
      - 'Gemfile.lock'
      - '**/*.rb'
      - '.github/workflows/test.yml'

env:
  AWS_REGION: ap-northeast-1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run rspec
        run: bundle exec rspec
